import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";
import os from "os";

const env = process.argv[2] || "production";
const prod = env === "production";
const useTestManifest = process.argv.includes("--test-manifest");

function readManifest() {
  const manifestPath = path.join(process.cwd(), "manifest.json");
  return JSON.parse(fs.readFileSync(manifestPath, "utf8"));
}

function buildTargetManifest(sourceManifest) {
  const idSuffix = useTestManifest
    ? process.env.OBSIDIAN_TEST_ID_SUFFIX || "-test"
    : process.env.OBSIDIAN_TEST_ID_SUFFIX || "";
  const nameSuffix = useTestManifest
    ? process.env.OBSIDIAN_TEST_NAME_SUFFIX || " TEST"
    : process.env.OBSIDIAN_TEST_NAME_SUFFIX || "";

  const targetManifest = {
    ...sourceManifest,
    id: `${sourceManifest.id}${idSuffix}`,
    name: `${sourceManifest.name}${nameSuffix}`,
  };

  return targetManifest;
}

if (prod) {
  dotenv.config({ path: ".env.production" });
} else {
  if (fs.existsSync(".env.local")) {
    dotenv.config({ path: ".env.local" });
  } else {
    dotenv.config({ path: ".env" });
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

/**
 * Writes one file into the plugin folder.
 *
 * Not fs.copyFileSync: that goes through copyfile(3), which also replicates
 * metadata and ACLs, and a File Provider folder (Dropbox, iCloud Drive,
 * OneDrive) rejects that with EPERM when the destination already exists.
 * Removing the old file first turns the overwrite into a plain create, which
 * those folders do allow.
 */
function writeIntoPlugin(destPath, contents) {
  try {
    fs.writeFileSync(destPath, contents);
    return;
  } catch (e) {
    if (e.code !== "EPERM" && e.code !== "EACCES") throw e;
  }

  // Hold on to what is installed. Removing it and then failing the retry too
  // would leave Obsidian with no main.js at all - worse than a stale one.
  let installed = null;
  try {
    installed = fs.readFileSync(destPath);
  } catch {
    installed = null;
  }

  fs.rmSync(destPath, { force: true });
  try {
    fs.writeFileSync(destPath, contents);
  } catch (e) {
    if (installed !== null) {
      try {
        fs.writeFileSync(destPath, installed);
      } catch {
        console.error(`Could not restore the previous ${destPath}.`);
      }
    }
    throw e;
  }
}

const copy_to_plugins = {
  name: "copy_to_plugins",
  setup(build) {
    build.onEnd(() => {
      let obsidianPluginsPath = process.env.OBSIDIAN_PLUGINS_PATH;

      if (!obsidianPluginsPath) {
        console.log(
          "OBSIDIAN_PLUGINS_PATH is not set. Skipping copy to plugins directory."
        );
        return;
      }

      if (obsidianPluginsPath.startsWith("~")) {
        obsidianPluginsPath = path.join(
          os.homedir(),
          obsidianPluginsPath.slice(1)
        );
      }

      const sourceManifest = readManifest();
      const targetManifest = buildTargetManifest(sourceManifest);
      const pluginDirName =
        process.env.OBSIDIAN_PLUGIN_DIR || targetManifest.id;
      const plugin_path = path.join(obsidianPluginsPath, pluginDirName);

      if (!fs.existsSync(plugin_path)) {
        fs.mkdirSync(plugin_path, { recursive: true });
      }

      try {
        writeIntoPlugin(
          path.join(plugin_path, "main.js"),
          fs.readFileSync("./main.js")
        );
        writeIntoPlugin(
          path.join(plugin_path, "manifest.json"),
          `${JSON.stringify(targetManifest, null, "\t")}\n`
        );
        writeIntoPlugin(
          path.join(plugin_path, "styles.css"),
          fs.readFileSync("./styles.css")
        );
        // add empty .hotreload file
        writeIntoPlugin(path.join(plugin_path, ".hotreload"), "");
      } catch (e) {
        if (e.code !== "EPERM" && e.code !== "EACCES") throw e;
        // Watch mode should keep running: the bundle is still built, it just
        // did not reach the vault.
        console.error(
          [
            `Could not write to ${plugin_path} (${e.code}).`,
            "The vault sits in a synced folder, so the process running this build needs access to it:",
            "  - System Settings > Privacy & Security > Full Disk Access, then add the terminal or editor running this build and restart it",
            "  - In the sync client, keep that folder available offline rather than online-only",
            "  - If the folder is locked: chflags -R nouchg '<plugin folder>'",
          ].join("\n")
        );
        return;
      }

      console.log(
        `Plugin built and copied to ${plugin_path} (manifest id: ${targetManifest.id})`
      );
    });
  },
};
const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  define: {
    "process.env.NODE_ENV": `"${prod ? "production" : "development"}"`,
    "process.env.OPENAI_API_KEY": `"${prod ? "" : process.env.OPENAI_API_KEY}"`,
    "process.env.GOOGLE_API_KEY": `"${prod ? "" : process.env.GOOGLE_API_KEY}"`,
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [copy_to_plugins],
});
if (!prod) await context.watch();
else {
  await context.rebuild();
  process.exit(0);
}
